export const LANDING = '/';
export const SIGN_UP = '/signup';
export const SIGN_IN = '/signin';
export const HOME = '/home';
export const ACCOUNT = '/account';
export const PASSWORD_FORGET = '/pw-forget';
export const ADMIN = '/admin';
export const PRICING = '/pricing';
export const WHYMINING = '/whymining';
export const ADMIN_DETAILS = '/admin/:id';
export const BLOG="/blog";
export const ABOUT ="/about";
export const CONTACTUS ="/contactus"
export const RADIANT ="/radiant-tech"
export const ENIGMA ="/enigma"
export const KYC ="/kycverify"